default_stages:
  - "commit"
  - "push"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-symlinks
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-xml
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: mixed-line-ending
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: check-merge-conflict
  - id: detect-private-key

- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: '2.6.2'
  hooks:
  - id: editorconfig-checker-system
    entry: editorconfig-checker

- repo: local
  hooks:
  - id: treefmt
    name: treefmt
    description: 'One CLI to format the code tree'
    entry: treefmt
    language: system
    types: [text]
    args: []
    require_serial: false
